name: stmr_cli
description: STMR CLI - Ferramenta de linha de comando para simplificar o desenvolvimento Flutter

version: 1.0.10

environment:
  sdk: ^3.0.0

executables:
  stmr:

dependencies:
  args: ^2.4.0
  yaml: ^3.1.2
  path: ^1.8.3
  mason_logger: ^0.2.15
  recase: ^4.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  mocktail: ^1.0.0
