name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  auto-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 0

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1

    - name: Get dependencies
      run: dart pub get

    - name: Get current version
      id: version
      run: |
        VERSION=$(grep "version:" pubspec.yaml | sed 's/version: //')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $VERSION"

    - name: Check if tag exists
      id: tag_check
      run: |
        if git rev-parse "v${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Tag v${{ steps.version.outputs.version }} already exists"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Tag v${{ steps.version.outputs.version }} does not exist"
        fi

    - name: Create tag and release
      if: steps.tag_check.outputs.exists == 'false'
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        VERSION=${{ steps.version.outputs.version }}
        
        # Criar tag
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "v$VERSION" -m "Release v$VERSION"
        git push origin "v$VERSION"
        
        # Criar release com release notes automáticas
        gh release create "v$VERSION" \
          --title "Release v$VERSION" \
          --generate-notes \
          --latest

    - name: Release created
      if: steps.tag_check.outputs.exists == 'false'
      run: |
        echo "✅ Release v${{ steps.version.outputs.version }} created successfully!"
        echo "🔗 Check it out: https://github.com/${{ github.repository }}/releases/tag/v${{ steps.version.outputs.version }}"

    - name: Tag already exists
      if: steps.tag_check.outputs.exists == 'true'
      run: |
        echo "⚠️  Tag v${{ steps.version.outputs.version }} already exists, skipping release creation" 